version: 0.0
os: linux
files:
  - source: ./ryyppynet.war
    destination: /opt/ryyppynet
hooks:
  ApplicationStart:
    - location: start_ryyppynet.sh
  ApplicationStop:
    - location: stop_ryyppynet.sh