import { createRequire } from 'module';
const require = createRequire(new URL('../../e2e/package.json', import.meta.url));
const { chromium } = require('playwright');
const browser = await chromium.launch({ executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE });
const ctx = await browser.newContext({ baseURL: 'http://localhost:8080', viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const css = 'img:not([src]), img[src=""], .drinker img { visibility:hidden !important; height:0 !important } .ui-pnotify{display:none !important}';
page.on('load', () => page.addStyleTag({ content: css }).catch(()=>{}));
const id = Date.now();
await page.goto('/ui/newuser');
await page.fill('#drinkerName', 'Mikko'); await page.fill('#email', `mikko2-${id}@example.com`);
await page.selectOption('#sex', 'MALE'); await page.fill('#drinkerWeight', '82');
await page.fill('#password', 'correct-horse-battery-staple'); await page.click('#submitButton');
await page.waitForURL(/app\/index/); await page.waitForTimeout(800);
await page.goto('/app/index.html#/party-admin/');
await page.fill('#partyName', 'Vappu 2026'); await page.click('button[type="submit"]');
await page.waitForURL(/#\/party\/\d+/);
const partyId = page.url().match(/party\/(\d+)/)[1];
for (const [name, sex, weight] of [['Aino','FEMALE',62],['Juha','MALE',90],['Laura','FEMALE',68]])
  await page.request.post(`/API/v2/parties/${partyId}/participants`, { form: { name, sex, weight } });
const parts = await (await page.request.get(`/API/v2/parties/${partyId}/participants`)).json();
const now = Date.now();
const plan = { Mikko: [170, 130, 95, 60, 30], Aino: [150, 100, 45], Juha: [175, 150, 120, 90, 70, 40, 15], Laura: [120, 50] };
for (const p of parts) for (const m of plan[p.name] || [])
  await page.request.post(`/API/v2/parties/${partyId}/participants/${p.id}/drinks`, { form: { timestamp: new Date(now - m*60000).toISOString() } });
await page.reload(); await page.waitForTimeout(2500);
await page.addStyleTag({ content: css });
const tile = page.locator('.drinker', { has: page.getByText('Mikko') });
await page.screenshot({ path: 'shots/c_party.png' });
await page.setViewportSize({ width: 390, height: 2100 }); await page.waitForTimeout(1200);
await page.screenshot({ path: 'shots/c_party_full.png' });
await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(1000);
await tile.screenshot({ path: 'shots/c_tile_before.png' });
await tile.locator('.container-fluid').first().click();
await page.waitForTimeout(1200); await tile.screenshot({ path: 'shots/c_tile_overlay.png' });
await tile.locator('.drinker-overlay').first().getByText('Muokkaa').click();
await page.waitForTimeout(500); await tile.screenshot({ path: 'shots/c_tile_edit.png' });
await tile.locator('.drinker-overlay').nth(1).getByRole('button', { name: 'Tallenna' }).click();
await page.waitForTimeout(1500);
await tile.screenshot({ path: 'shots/c_tile_after.png' });
console.log(await tile.innerText());
await browser.close();
