version: "3.9"
services:
  postgres:
    image: "postgres:14.1"
    restart: always
    env_file:
      - postgres/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/

volumes:
  pgdata: