#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $RYYPPYNET_DB_USER WITH PASSWORD '$RYYPPYNET_DB_PASSWORD';
    CREATE DATABASE $RYYPPYNET_DB;
    GRANT ALL PRIVILEGES ON DATABASE $RYYPPYNET_DB TO $RYYPPYNET_DB_USER;
EOSQL